version: "3.9"

services:
  php:
    container_name: furgonetka-rest-api-php
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env
    tty: true
    volumes:
      - ./:/app